import * as vscode from 'vscode';
import * as fs from 'fs/promises';
import * as path from 'path';
import ExcelJS from 'exceljs';

export function registerConvertExcelToTabularxCommand(context: vscode.ExtensionContext) {
  const disposable = vscode.commands.registerCommand('lingtex.convertExcelToTabularx', async () => {
    const input = await vscode.window.showOpenDialog({
      canSelectFiles: true,
      canSelectFolders: false,
      canSelectMany: false,
      filters: { 'Excel': ['xlsx'], 'All Files': ['*'] }
    });
    if (!input || input.length === 0) { return; }
    const inputPath = input[0].fsPath;

    await vscode.window.withProgress({ location: vscode.ProgressLocation.Notification, title: 'LingTeX: Excel → LaTeX tabularx', cancellable: false }, async (progress) => {
      progress.report({ message: 'Reading workbook…' });
      const wb = new ExcelJS.Workbook();
      await wb.xlsx.readFile(inputPath);
      const ws = wb.worksheets[0];
      if (!ws) {
        vscode.window.showErrorMessage('No worksheet found');
        return;
      }

      progress.report({ message: 'Generating LaTeX…' });
      const table = worksheetToTabularx(ws);

      const cfg = vscode.workspace.getConfiguration('lingtex');
      const outDirSetting = cfg.get<string>('tables.outputDir');
      const outDir = expandWorkspaceFolder(outDirSetting || '${workspaceFolder}/misc/tables');
      await fs.mkdir(outDir, { recursive: true });
      const outName = path.basename(inputPath, path.extname(inputPath)) + '.tabularx.tex';
      const outPath = path.join(outDir, outName);

      await fs.writeFile(outPath, table, 'utf8');
      vscode.window.showInformationMessage(`LingTeX: Wrote tabularx to ${outPath}`);
      await vscode.window.showTextDocument(vscode.Uri.file(outPath));
    });
  });
  context.subscriptions.push(disposable);
}

function worksheetToTabularx(ws: ExcelJS.Worksheet): string {
  const rows: string[][] = [];
  let maxCols = 0;
  ws.eachRow((row) => {
    const cells: string[] = [];
    row.eachCell((cell) => {
      const v = cell.text?.toString?.() ?? cell.value?.toString?.() ?? '';
      cells.push(latexEscape(v));
    });
    maxCols = Math.max(maxCols, cells.length);
    rows.push(cells);
  });
  const colSpec = Array(maxCols).fill('X').join('');
  const body = rows.map(r => r.concat(Array(maxCols - r.length).fill('')).join(' & ') + ' \\').join('\n');
  return [
    '% Generated by LingTeX',
    '\\begin{tabularx}{\\textwidth}{' + colSpec + '}',
    body,
    '\\end{tabularx}',
    ''
  ].join('\n');
}

function expandWorkspaceFolder(p: string): string {
  const ws = vscode.workspace.workspaceFolders?.[0];
  if (!ws) return p;
  return p.replace('${workspaceFolder}', ws.uri.fsPath);
}

function latexEscape(s: string): string {
  return s
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([#%&_{}])/g, '{\\$1}')
    .replace(/\^/g, '{\\textasciicircum}')
    .replace(/~/g, '{\\textasciitilde}');
}
